DjBoe/urls.py
from django.conf.urls import patterns, include, url
from django.core.urlresolvers import reverse

from django.contrib import admin
from django.views.generic.base import TemplateView
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    url(r'^$', TemplateView.as_view(template_name='acerca.html'), name="acerca"),
    url('', include('boe.core.urls', namespace='boe')),
    url('', include('boe.web.urls')),
    url('', include('boe.scaner.urls', namespace='boescan')),
    url('', include('social.apps.django_app.urls', namespace='social')),
    url(r'^admin/', include(admin.site.urls)),
)

urlpatterns += patterns('django.contrib.auth.views',
    url(r'^login/$', 'login', { 'template_name': 'registration/login.html' }, name='login' ),
    url(r'^logout/$', 'logout', name='logout' ),
)

boe/core/urls.py
from django.conf.urls import url
from boe.core.views import *

urlpatterns = [
    url(r'^reglas/$', reglas, name='reglas'),
    url(r'^regla/add/(?P<rule_type>\w+)/$', add_regla, name='add_regla'),
    url(r'^regla/details/(?P<regla_id>\d+)/$', details_regla, name='details_regla'),
    # url(r'^regla/details/(?P<alias>\w+)/$', 'details_regla', name='details_regla'),
]

boe/scaner/urls.py
from django.conf.urls import url
from boe.scaner.views import *

urlpatterns = [
    url(r'^alertas/$', alertas, name='alertas'),

    url(r'^run/$', run_hoy, name='run'),
    url(r'^status/$', status, name='status'),
    url(r'^run/(?P<boe_id>BOE-[SAB][\d-]+)/$', run_boe, name='run_boe'),
]

boe/web/urls.py
from django.conf.urls import url
from boe.web.views import *

urlpatterns = [
    # url(r'^$', views.acerca, name='acerca'),
    url(r'^perfil/$', perfil, name='perfil'),
]

boe/scaner/models.py
from __future__ import unicode_literals

from django.db import models
from django.contrib.auth.models import User
from boe.core.models import Regla


class Boe(models.Model):
    boe = models.CharField(max_length=20, unique=True)
    fecha = models.DateField(auto_now_add=True)
    error = models.BooleanField(default=False)
    error_text = models.CharField(max_length=254, null=True, blank=True)
    celery_task = models.CharField(max_length=255, null=True, blank=True)

    def __unicode__(self):
        return self.boe


class AlertaUsuario(models.Model):
    user = models.ForeignKey(User, related_name='alertas')
    regla = models.ForeignKey(Regla)
    boe = models.ForeignKey(Boe, related_name='+')
    enviado = models.BooleanField(default=False)
    fecha_envio = models.DateTimeField(null=True, blank=True)

boe/core/forms.py
from __future__ import unicode_literals

from django.utils.translation import ugettext_lazy as _

from django.contrib.auth.models import User
from django.db import models
from django import forms

from boe.core.models import Regla
from boe.core.models import ReglaS
from boe.core.models import ReglaA
from boe.core.models import ReglaB
from boe.core.models import RegexValidator
from boe.core.models import ExpresionRegular


class ReglaForm(forms.ModelForm):
    class Meta:
        model = Regla
        exclude = ('user',)

    def save(self, commit=True, user=None):
        regla = None
        try:
            regla = Regla.objects.get(user=user, alias=self.cleaned_data["alias"])
        except Regla.DoesNotExist:
            regla = super(ReglaForm, self).save(commit=False)
            if commit:
                if user:
                    regla.user = user
                regla.save()
        return regla


class ReglaRapidaForm(forms.ModelForm):
    expresion = forms.CharField(max_length=254, validators=[RegexValidator])

    class Meta:
        model = Regla
        exclude = ('user',)

    def clean_expresion(self):
        ret = None
        if self.cleaned_data["expresion"]:
            try:
                ret = ExpresionRegular.objects.get(re_exp=self.cleaned_data["expresion"])
            except ExpresionRegular.DoesNotExist:
                ret = ExpresionRegular.objects.create(re_exp=self.cleaned_data["expresion"])
        return ret

    def save(self, commit=True, user=None):
        regla = None
        try:
            regla = Regla.objects.get(user=user, alias=self.cleaned_data["alias"])
        except Regla.DoesNotExist:
            regla = super(ReglaRapidaForm, self).save(commit=False)
            if commit:
                if user:
                    regla.user = user
                regla.save()
        return regla


class ReglaSForm(forms.ModelForm):
    titulo = models.CharField(max_length=254, unique=True, validators=[RegexValidator])

    class Meta:
        model = ReglaS
        exclude = ('regla', 're_titulo',)

    def save(self, commit=True, regla=None):
        subregla = super(ReglaSForm, self).save(commit=False)
        if commit:
            try:
                subregla.re_titulo = ExpresionRegular.objects.get(re_exp=self.cleaned_data["titulo"])
            except ExpresionRegular.DoesNotExist:
                subregla.re_titulo = ExpresionRegular.objects.create(re_exp=self.cleaned_data["titulo"])
            if regla:
                subregla.regla = regla
            subregla.save()
        return regla


class ReglaAForm(forms.ModelForm):
    titulo = models.CharField(max_length=254, unique=True, validators=[RegexValidator])
    texto = models.CharField(max_length=254, unique=True, validators=[RegexValidator])

    class Meta:
        model = ReglaA
        exclude = ('regla', 're_titulo', 're_texto',)

    def save(self, commit=True, regla=None):
        subregla = super(ReglaAForm, self).save(commit=False)
        if commit:
            try:
                subregla.re_titulo = ExpresionRegular.objects.get(re_exp=self.cleaned_data["titulo"])
            except ExpresionRegular.DoesNotExist:
                subregla.re_titulo = ExpresionRegular.objects.create(re_exp=self.cleaned_data["titulo"])
            try:
                subregla.re_texto = ExpresionRegular.objects.get(re_exp=self.cleaned_data["texto"])
            except ExpresionRegular.DoesNotExist:
                subregla.re_texto = ExpresionRegular.objects.create(re_exp=self.cleaned_data["texto"])
            if regla:
                subregla.regla = regla
            subregla.save()
        return regla


class ReglaBForm(forms.ModelForm):
    titulo = models.CharField(max_length=254, unique=True, validators=[RegexValidator])
    texto = models.CharField(max_length=254, unique=True, validators=[RegexValidator])

    class Meta:
        model = ReglaB
        exclude = ('regla', 're_titulo', 're_texto',)

    def save(self, commit=True, regla=None):
        subregla = super(ReglaBForm, self).save(commit=False)
        if commit:
            try:
                subregla.re_titulo = ExpresionRegular.objects.get(re_exp=self.cleaned_data["titulo"])
            except ExpresionRegular.DoesNotExist:
                subregla.re_titulo = ExpresionRegular.objects.create(re_exp=self.cleaned_data["titulo"])
            try:
                subregla.re_texto = ExpresionRegular.objects.get(re_exp=self.cleaned_data["texto"])
            except ExpresionRegular.DoesNotExist:
                subregla.re_texto = ExpresionRegular.objects.create(re_exp=self.cleaned_data["texto"])
            if regla:
                subregla.regla = regla
            subregla.save()
        return regla

boe/core/views.py
from django.shortcuts import render_to_response
from django.shortcuts import redirect
from django.shortcuts import get_object_or_404
from django.template import RequestContext
from django.contrib.auth.decorators import login_required
from django.views.decorators.csrf import csrf_protect
from django.http import HttpResponse

from boe.core.forms import ReglaForm
from boe.core.forms import ReglaSForm
from boe.core.forms import ReglaAForm
from boe.core.forms import ReglaBForm
from boe.core.forms import ReglaRapidaForm
from boe.core.models import Regla
from boe.core.models import ReglaA
from boe.core.models import ReglaB
from boe.core.models import ReglaS


@login_required
def reglas(request, rule_type=None):
    context = {
        'cls_basico': 'active',
        'cls_avanzado': ''
    }
    context['regla_form'] = ReglaForm()
    context['rapida_form'] = ReglaRapidaForm()
    context['s_form'] = ReglaSForm()
    context['a_form'] = ReglaAForm()
    context['b_form'] = ReglaBForm()
    context['reglas'] = Regla.objects.filter(user=request.user)

    '''
    t = ExpresionRegular.objects.filter(s_titulo__isnull=False)
    context['testing'] = []
    for re_exp in t:
        context['testing'].append( re_exp.s_titulo.filter(regla__alertausuario__regla__isnull=True) )
    #'''
    return render_to_response('boe/reglas.html', context, RequestContext(request))


@csrf_protect
@login_required
def add_regla(request, rule_type=None):
    context = {
        'cls_basico': '',
        'cls_avanzado': ''
    }
    context['regla_form'] = ReglaForm()
    context['rapida_form'] = ReglaRapidaForm()
    context['s_form'] = ReglaSForm()
    context['a_form'] = ReglaAForm()
    context['b_form'] = ReglaBForm()
    if request.method == 'POST':
        form = None
        if rule_type == "A":
            context['a_form'] = ReglaAForm(request.POST)
            form = context['a_form']
        elif rule_type == "B":
            context['b_form'] = ReglaBForm(request.POST)
            form = context['b_form']
        elif rule_type == "S":
            context['s_form'] = ReglaSForm(request.POST)
            form = context['s_form']
        elif rule_type == "rapida":
            context['rapida_form'] = ReglaRapidaForm(request.POST)
            form = context['rapida_form']
        if form and form.is_valid():
            if rule_type in ['A', 'B', 'S']:
                context['regla_form'] = ReglaForm(request.POST)
                if context['regla_form'].is_valid():
                    regla = context['regla_form'].save(True, request.user)
                    subregla = form.save(True, regla)
                    return redirect('boe:reglas')
                context['cls_avanzado'] = 'active'
            else:
                regla = form.save(True, request.user)
                rexpresion = form.cleaned_data["expresion"]
                ReglaS.objects.create(regla=regla, re_titulo=rexpresion)
                ReglaA.objects.create(re_texto=rexpresion, regla=regla)
                ReglaA.objects.create(re_titulo=rexpresion, regla=regla)
                ReglaB.objects.create(re_texto=rexpresion, regla=regla)
                ReglaB.objects.create(re_titulo=rexpresion, regla=regla)
                return redirect('boe:reglas')
    context['reglas'] = Regla.objects.filter(user=request.user)
    if context['cls_avanzado'] == '':
        context['cls_basico'] = 'active'
    return render_to_response('boe/reglas.html', context, RequestContext(request))


@csrf_protect
@login_required
def details_regla(request, regla_id):
    regla = get_object_or_404(Regla, pk=regla_id, user=request.user)
    if request.method == 'POST':
        for id in request.POST.getlist('borrara[]'):
            try:
                dregla = ReglaA.objects.get(pk=id, regla=regla)
                dregla.delete()
            except ReglaA.DoesNotExist:
                pass
        for id in request.POST.getlist('borrarb[]'):
            try:
                dregla = ReglaB.objects.get(pk=id, regla=regla)
                dregla.delete()
            except ReglaB.DoesNotExist:
                pass
        for id in request.POST.getlist('borrars[]'):
            try:
                dregla = ReglaS.objects.get(pk=id, regla=regla)
                dregla.delete()
            except ReglaS.DoesNotExist:
                pass

    context = {'regla': regla}
    return render_to_response('boe/detalles.html', context, RequestContext(request))

boe/scaner/views.py
from django.conf import settings
from django.http import Http404
from django.http import HttpResponse
from django.shortcuts import redirect
from django.contrib.auth.decorators import login_required

from celery.task.control import inspect
from datetime import date
import httplib
import logging

from boe.scaner.parser import BoeDiaParser
from boe.scaner.utils import wget_url
from boe.scaner.tasks import procesa_boe, procesa
from boe.scaner.models import Boe
from djcelery.models import TaskMeta
from kombu.transport.django.models import Message
from celery.states import ALL_STATES

from django.shortcuts import render_to_response
from django.shortcuts import get_object_or_404
from django.template import RequestContext


@login_required
def alertas(request):
    '''
    perfil = get_object_or_404(Perfil, user=request.user)
    print request.user.alertas.all()
    print request.user.alertas.count()
    lista_alertas = AlertaUsuario.objects.filter(user=request.user)
    print lista_alertas
    #'''
    return render_to_response('boe/alertas.html', {}, RequestContext(request))


@login_required
def run_hoy(request):
    hoy = date.today()
    boe_parser = BoeDiaParser(hoy)
    boes = Boe.objects.filter(fecha=hoy, boe__startswith='BOE-S')
    if boes.count() > 0:
        return redirect('boescan:run_boe', boes[0].boe)
    else:
        (contenido, headers, estado) = wget_url(boe_parser.url, settings.PROXY)
        if estado == httplib.OK:
            boe_parser.feed(contenido.decode('utf-8', 'replace'))
            if boe_parser.boe:
                boe_id = Boe.objects.create(boe=boe_parser.boe, fecha=hoy)
                return redirect('boescan:run_boe', boe_parser.boe)
        logging.info("Respuesta %s Cabezeras %s" % (estado, headers))
    raise Http404


@login_required
def run_boe(request, boe_id):
    boe_obj = get_object_or_404(Boe, boe=boe_id)
    result = None
    if not boe_obj.celery_task:
        result = procesa_boe(boe_id)
    else:
        result = procesa.AsyncResult(boe_obj.celery_task)

    context = {
        'boe': boe_obj,
        'result': result
    }
    return render_to_response('boe/scaner.html', context, RequestContext(request))


# @login_required
def status(request):
    response_data = {}

    if request.user.is_staff:
        i = inspect()
        response_data['active'] = i.active()
        response_data['stats'] = i.stats()

        boes_error = Boe.objects.filter(error=True)
        response_data['error'] = []
        for er in boes_error.all():
            response_data['error'].append({
                'error_text': er.error_text,
                # 'task':er.celery_task,
                'boe': er.boe
            })

    msgs = Message.objects.filter(queue__name="celery")
    response_data['tasks'] = msgs.count()
    response_data['tasks_done'] = 0
    import json, base64
    for msg in msgs.all():
        payload = json.loads(msg.payload)
        task_id = payload['properties']['correlation_id']
        body = payload['body']
        if payload['properties']['body_encoding'] == 'base64':
            body = base64.b64decode(body)
        try:
            if procesa.AsyncResult(task_id).status == 'SUCCESS':
                response_data['tasks_done'] += 1
                '''
                print payload
                print task_id
                print body,"\n"
                #'''
        except:
            '''
            print payload
            print task_id
            print body,"\n"
            #'''
            pass

    for taskstatus in ALL_STATES:
        response_data[taskstatus.lower()] = TaskMeta.objects.filter(status=taskstatus).count()

    if response_data['failure'] > 0:
        response_data['failure_tasks'] = []
        failtasks = TaskMeta.objects.filter(status='FAILURE')
        for task in failtasks:
            response_data['failure_tasks'].append({
                'task_id': task.task_id
                , 'traceback': task.traceback
            })
    return HttpResponse(json.dumps(response_data), content_type="application/json")

boe/web/views.py
from django.shortcuts import render_to_response
from django.shortcuts import get_object_or_404
from django.template import RequestContext
from django.contrib.auth.decorators import login_required
from django.views.decorators.csrf import csrf_protect

from boe.web.forms import PerfilForm
from boe.web.models import Perfil


@csrf_protect
@login_required
def perfil(request):
    perfil = get_object_or_404(Perfil, user=request.user)
    form = PerfilForm(instance=perfil)
    if request.method == 'POST':
        form = PerfilForm(request.POST, instance=perfil)
        form.user = request.user
        if form.is_valid():
            model = form.save(commit=False)
            model.user = request.user
            model.save()
    context = {
        'form': form,
        'perfil': perfil
    }
    return render_to_response('boe/perfil.html', context, RequestContext(request))

boe/core/templates/boe/detalles.html
{% extends 'base.html' %}
{% load url from future %}
{% load i18n %}

{% block content_title %}{% trans 'detalles' %}{% endblock %}
{% block content %}
<form id="datos_usuario" method="POST" role="form" action="" >
{% csrf_token %}
<div class="panel panel-primary">
<div class="panel-heading"><h1 class="panel-title">{% trans 'Datos de la regla' %} {{ regla.alias }}</h1></div>
<div class="panel-body">

<fieldset class="panel panel-info">
<div class="panel-heading"><legend class="panel-title">{% trans 'Reglas S' %}:</legend></div>
<table cellpadding="0" cellspacing="0" border="0" class="display">
<thead>
<tr>
	<th>{% trans 'titulo' %}</th>
	<th>{% trans 'seccion' %}</th>
	<th>{% trans 'departamento' %}</th>
	<th>{% trans 'epigrafe' %}</th>
	<th></th>
</tr>
</thead>
<tbody>
{% for rs in regla.s.all %}
<tr>
	<td>{%if rs.re_titulo %} {{rs.re_titulo}} {% endif %}</td>
	<td>{%if rs.seccion %} {{rs.seccion}} {% endif %}</td>
	<td>{%if rs.departamento %} {{rs.departamento}} {% endif %}</td>
	<td>{%if rs.epigrafe %} {{rs.epigrafe}} {% endif %}</td>
	<td><input value="{{rs.id}}" type="checkbox" name="borrars[]"/></td>
</tr>
{% endfor %}
</tbody>
</table>
</fieldset>

<fieldset class="panel panel-info">
<div class="panel-heading"><legend class="panel-title">{% trans 'Reglas A' %}:</legend></div>
<table cellpadding="0" cellspacing="0" border="0" class="display">
<thead>
<tr>
	<th>{% trans 'titulo' %}</th>
	<th>{% trans 'texto' %}</th>
	<th>{% trans 'departamento' %}</th>
	<th>{% trans 'origen legislativo' %}</th>
	<th>{% trans 'materias' %}</th>
	<th>{% trans 'alertas' %}</th>
	<th></th>
</tr>
</thead>
<tbody>
{% for ra in regla.a.all %}
<tr>
	<td>{%if ra.re_titulo %} {{ra.re_titulo}} {% endif %}</td>
	<td>{%if ra.re_texto %} {{ra.re_texto}} {% endif %}</td>
	<td>{%if ra.departamento %} {{ra.departamento}} {% endif %}</td>
	<td>{%if ra.origen_legislativo %} {{ra.origen_legislativo}} {% endif %}</td>
	<td>{%if ra.materias %} {{ra.materias}} {% endif %}</td>
	<td>{%if ra.alertas %} {{ra.alertas}} {% endif %}</td>
	<td><input value="{{ra.id}}" type="checkbox" name="borrara[]"/></td>
</tr>
{% endfor %}
</tbody>
</table>
</fieldset>

<fieldset class="panel panel-info">
<div class="panel-heading"><legend class="panel-title">{% trans 'Reglas B' %}:</legend></div>
<table cellpadding="0" cellspacing="0" border="0" class="display" id="$table_id">
<thead>
<tr>
	<th>{% trans 'titulo' %}</th>
	<th>{% trans 'texto' %}</th>
	<th>{% trans 'departamento' %}</th>
	<th>{% trans 'materias cpv' %}</th>
	<th></th>
</tr>
</thead>
<tbody>
{% for rb in regla.b.all %}
<tr>
	<td>{%if rb.re_titulo %} {{rb.re_titulo}} {% endif %}</td>
	<td>{%if rb.re_texto %} {{rb.re_texto}} {% endif %}</td>
	<td>{%if rb.departamento %} {{rb.departamento}} {% endif %}</td>
	<td>{%if rb.materias_cpv %} {{rb.materias_cpv}} {% endif %}</td>
	<td><input value="{{rb.id}}" type="checkbox" name="borrarb[]"/></td>
</tr>
{% endfor %}
</tbody>
</table>
</fieldset>

<input type="submit" value="{% trans 'Borrar marcados' %}" class="btn btn-primary"/>
</form>
{% endblock %}

boe/core/templates/boe/reglas.html
{% extends 'base.html' %}
{% load url from future %}
{% load i18n %}

{% block content_title %}{% trans 'reglas' %}{% endblock %}
{% block content %}
<div class="panel panel-primary" id="admin_reglas">
<div class="panel-heading">
<ul class="nav nav-tabs">
<li class="active"><a href="#basico" data-toggle="tab">Reglas Basica</a></li>
<li><a href="#avanzado" data-toggle="tab">Reglas Avanzada</a></li>
<li><a href="#ayuda" data-toggle="tab">Ayuda</a></li>
</ul>
</div>

<div class="tab-content">
<div class="tab-pane {{cls_basico}}" id="basico">
<form id="regla_rapida" method="POST" role="form" action="{% url 'boe:add_regla' 'rapida' %}" >
{% csrf_token %}
<fieldset class="panel panel-info">
<div class="panel-heading"><span class="glyphicon"></span>
<legend class="panel-title">{% trans 'regla rapida' %}:</legend></div>
{{ rapida_form.alias.errors }}
<label>{{ rapida_form.alias.label }}
	{{ rapida_form.alias }}
</label>
{{ rapida_form.expresion.errors }}
<label>{{ rapida_form.expresion.label }}
	{{ rapida_form.expresion }}
</label>
{{ rapida_form.malformado.errors }}
<label>{{ rapida_form.malformado.label }}
	{{ rapida_form.malformado }}
</label>
<input type="submit" value="{% trans 'guardar' %}" class="btn btn-primary"/>
</fieldset>
</form>
{% block lista_reglas %}
<div class="panel panel-info">
<div class="panel-heading"><span class="panel-title">{% trans 'Lista de reglas' %}:</span></div>
<ul>
{% for r in reglas %}
	<li><a href="{% url 'boe:details_regla' r.pk %}">{{ r.alias }}</a><span class="badge">{{r.s.count}}/{{r.a.count}}/{{r.b.count}}</span></li>
{% endfor %}
</ul>
</div>
{% endblock %}
</div>
<div class="tab-pane {{cls_avanzado}}" id="avanzado">
<!-- TODO INSERTAR FORMULARIOS -->

<form id="regla_rapida" method="POST" role="form" action="{% url 'boe:add_regla' 'S' %}" >
{% csrf_token %}
<fieldset class="panel panel-info">
<div class="panel-heading"><span class="glyphicon"></span>
<legend class="panel-title">{% trans 'regla S' %}:</legend></div>
{{ regla_form }}
{{ s_form }}
</fieldset>
<input type="submit" value="{% trans 'guardar' %}" class="btn btn-primary"/>
</form>
<form id="regla_rapida" method="POST" role="form" action="{% url 'boe:add_regla' 'A' %}" >
{% csrf_token %}
<fieldset class="panel panel-info">
<div class="panel-heading"><span class="glyphicon"></span>
<legend class="panel-title">{% trans 'regla A' %}:</legend></div>
{{ regla_form }}
{{ a_form }}
</fieldset>
<input type="submit" value="{% trans 'guardar' %}" class="btn btn-primary"/>
</form>
<form id="regla_rapida" method="POST" role="form" action="{% url 'boe:add_regla' 'B' %}" >
{% csrf_token %}
<fieldset class="panel panel-info">
<div class="panel-heading"><span class="glyphicon"></span>
<legend class="panel-title">{% trans 'regla B' %}:</legend></div>
{{ regla_form }}
{{ b_form }}
</fieldset>
<input type="submit" value="{% trans 'guardar' %}" class="btn btn-primary"/>
</form>

</div>
<div class="tab-pane" id="ayuda">
<div class="panel panel-info">
{% block ayuda_content %}
<div class="panel-heading">Sobre el funcionamiento de las Reglas</div>
<p>En el panel de busqueda avanzada podemos ver tres tipo de "BOE"s.<br/>
Cada uno de ellos contiene un formato diferente y por tanto las alertas se puede configurar con distintas opciones.</p>
<div class="alert alert-danger">Si una regla tiene varias opciones selecciondas, todas ellas han de ser ciertas para poder notificar la Alerta.</div>
<h3>BOE del tipo S</h3>
<p>Este BOE es el formato "inicial" donde aparecen listado el resto de BOEs.<br/>
Sobre este formato existen las siguientes opciones:
<ul>
<li><b>seccion:</b> Es un listado con las distintas secciones posibles.</li>
<li><b>departamento:</b> Es un listado con los distintos departamentos posibles.</li>
<li><b>epigrafe:</b> Es un listado con los distintos epigrafes posibles.</li>
<li><b>titulo:</b> <a href="http://docs.python.org/2/library/re.html#regular-expression-syntax">Expresion regular</a> usada para buscar en el titulo.</li>
</ul>
</p>
<h3>BOE del tipo A</h3>
<p>Este BOE es el formato legislativo.<br/>
Sobre este formato existen las siguientes opciones:
<ul>
<li><b>titulo:</b> <a href="http://docs.python.org/2/library/re.html#regular-expression-syntax">Expresion regular</a> usada para buscar en el titulo.</li>
<li><b>departamento:</b> Es un listado con los distintos departamentos posibles.</li>
<li><b>origen legislativo:</b> Es un listado con los distintos ordenes legislativos.</li>
<li><b>materias:</b> .</li>
<li><b>alertas:</b> Es un listado de posibles alerta como parecen en "Alertas legislativas" y "Nombramientos, oposiciones y concursos" en el servicio oficial.</li>
<li><b>texto:</b> <a href="http://docs.python.org/2/library/re.html#regular-expression-syntax">Expresion regular</a> usada para buscar en el texto del BOE.</li>
</ul>
</p>
<h3>BOE del tipo B de licitaciones</h3>
<p>Este BOE es el formato.<br/>Sobre este formato existen las siguientes opciones:
<ul>
<li><b>titulo:</b> <a href="http://docs.python.org/2/library/re.html#regular-expression-syntax">Expresion regular</a> usada para buscar en el titulo.</li>
<li><b>departamento:</b> Es un listado con los distintos departamentos posibles.</li>
<li><b>materias:</b> Es un listado de posibles alerta como parecen en "Alertas de anuncios de licitación" en el servicio oficial.</li>
<li><b>texto:</b> <a href="http://docs.python.org/2/library/re.html#regular-expression-syntax">Expresion regular</a> usada para buscar en el texto del BOE.</li>
</ul>
</p>
{% endblock %}
</div>
</div>

</div>
</div>

{% endblock %}