DjBoe/urls.py
from django.conf.urls import patterns, include, url
from django.core.urlresolvers import reverse

from django.contrib import admin
from django.views.generic.base import TemplateView
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    url(r'^$', TemplateView.as_view(template_name='acerca.html'), name="acerca"),
    url('', include('boe.core.urls', namespace='boe')),
    url('', include('boe.web.urls')),
    url('', include('boe.scaner.urls', namespace='boescan')),
    url('', include('social.apps.django_app.urls', namespace='social')),
    url(r'^admin/', include(admin.site.urls)),
)

urlpatterns += patterns('django.contrib.auth.views',
    url(r'^login/$', 'login', { 'template_name': 'registration/login.html' }, name='login' ),
    url(r'^logout/$', 'logout', name='logout' ),
)

boe/core/urls.py
from django.conf.urls import url
from boe.core.views import *

urlpatterns = [
    url(r'^reglas/$', reglas, name='reglas'),
    url(r'^regla/add/(?P<rule_type>\w+)/$', add_regla, name='add_regla'),
    url(r'^regla/details/(?P<regla_id>\d+)/$', details_regla, name='details_regla'),
    # url(r'^regla/details/(?P<alias>\w+)/$', 'details_regla', name='details_regla'),
]

boe/scaner/urls.py
from django.conf.urls import url
from boe.scaner.views import *

urlpatterns = [
    url(r'^alertas/$', alertas, name='alertas'),

    url(r'^run/$', run_hoy, name='run'),
    url(r'^status/$', status, name='status'),
    url(r'^run/(?P<boe_id>BOE-[SAB][\d-]+)/$', run_boe, name='run_boe'),
]

templates/acerca.html
{% extends "base.html" %}
{% load url from future %}
{% load i18n %}

{% block content %}
<h2>Acerda de:</h2>
<p>Sistema de procesado y alertar para el <a href="http://www.boe.es/">BOE (Boletin Oficial del Estado)</a>.</p>
<p><a href="https://github.com/ehooo/BOE_Alert">{% trans 'Disponible en Github' %}</a></p>
{% endblock %}

templates/base.html
{% load url from future %}
{% load staticfiles %}
{% load i18n %}
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>{% trans 'Alertas del BOE' %} {% block content_title %}{% endblock %}</title>
<link rel="author" title="About" href="{% url 'acerca' %}" />
<link rel="copyright" title="Copyright" href="http://www.gnu.org/licenses/gpl-2.0.html" />
<link rel="shortcut icon" type="image/png" href="{% static 'img/icon.png' %}" />

<!-- jQuery -->
<script src="{% static 'js/jquery.min.js' %}"></script>

<!-- DataTables -->
<script src="{% static 'js/jquery.datatables.min.js' %}"></script>
<link rel="stylesheet" href="{% static 'css/jquery.dataTables.css' %}" />

<!-- Bootstrap -->
<script src="{% static 'js/bootstrap.min.js' %}"></script>
<link rel="stylesheet" href="{% static 'css/bootstrap.css' %}" />

<!-- Boe -->
<link rel="stylesheet" type="text/css" href="{% static 'boe/boe.css' %}"/>
<script src="{% static 'boe/boe.js' %}"></script>
{% block addheader %}{% endblock %}
</head>
<body>

<div class="container">
<div class="header">
{% block sidebar %}
<ul class="nav nav-pills pull-right">
{% url 'boescan:alertas' as uri_alertas %}
	<li class="{% ifequal request.path uri_alertas %}active{% endifequal %}"><a href="{{uri_alertas}}">{% trans 'alertas' %}
	<span id="total_alertas" class="badge">{{ user.alertas.count }}</span></a></li>
{% url 'perfil' as uri_perfil %}
	<li class="{% ifequal request.path uri_perfil %}active{% endifequal %}"><a href="{{uri_perfil}}">{% trans 'perfil' %}</a></li>
{% url 'boe:reglas' as uri_reglas %}
	<li class="{% ifequal request.path uri_reglas %}active{% endifequal %}"><a href="{{uri_reglas}}">{% trans 'reglas' %}</a></li>
	{% if user.is_authenticated %}<li><a href="{% url 'logout' %}">{% trans 'logout' %}</a></li>{% endif %}
</ul>
{% endblock %}
<a href="{% url 'acerca' %}"><h3 class="text-muted">{% trans 'Alertas del BOE' %}</h3></a>
</div>
{% block content %}{% endblock %}
</div>
</body>

templates/reglas.html
$def with (errores, tablaRapida, tablaS, tablaA, tablaB)
$var seccion: reglas

$if errores is not None:
	$if len(errores) > 0:
		$for error in errores:
			<div class="alert alert-danger">$error</div>
	$else:
		<div class="alert alert-success">Datos guardados</div>

<div class="panel panel-primary" id="admin_reglas">
<div class="panel-heading">
<ul class="nav nav-tabs">
<li class="active"><a href="#basico" data-toggle="tab">Reglas Basica</a></li>
<li><a href="#avanzado" data-toggle="tab">Reglas Avanzada</a></li>
<li><a href="#ayuda" data-toggle="tab">Ayuda</a></li>
</ul>
</div>

<div class="tab-content">
<div class="tab-pane active" id="basico">
$:tablaRapida
</div>
<div class="tab-pane" id="avanzado">
$:tablaS
$:tablaA
$:tablaB
</div>
<div class="tab-pane" id="ayuda">
<div class="panel panel-info">
<div class="panel-heading">Sobre el funcionamiento de las Reglas</div>
<p>En el panel de busqueda avanzada podemos ver tres tipo de "BOE"s.<br/>
Cada uno de ellos contiene un formato diferente y por tanto las alertas se puede configurar con distintas opciones.</p>
<div class="alert alert-danger">Si una regla tiene varias opciones selecciondas, todas ellas han de ser ciertas para poder notificar la Alerta.</div>
<h3>BOE del tipo S</h3>
<p>Este BOE es el formato "inicial" donde aparecen listado el resto de BOEs.<br/>
Sobre este formato existen las siguientes opciones:
<ul>
<li><b>seccion:</b> Es un listado con las distintas secciones posibles.</li>
<li><b>departamento:</b> Es un listado con los distintos departamentos posibles.</li>
<li><b>epigrafe:</b> Es un listado con los distintos epigrafes posibles.</li>
<li><b>titulo:</b> <a href="http://docs.python.org/2/library/re.html#regular-expression-syntax">Expresion regular</a> usada para buscar en el titulo.</li>
</ul>
</p>
<h3>BOE del tipo A</h3>
<p>Este BOE es el formato legislativo.<br/>
Sobre este formato existen las siguientes opciones:
<ul>
<li><b>titulo:</b> <a href="http://docs.python.org/2/library/re.html#regular-expression-syntax">Expresion regular</a> usada para buscar en el titulo.</li>
<li><b>departamento:</b> Es un listado con los distintos departamentos posibles.</li>
<li><b>origen legislativo:</b> Es un listado con los distintos ordenes legislativos.</li>
<li><b>materias:</b> .</li>
<li><b>alertas:</b> Es un listado de posibles alerta como parecen en "Alertas legislativas" y "Nombramientos, oposiciones y concursos" en el servicio oficial.</li>
<li><b>texto:</b> <a href="http://docs.python.org/2/library/re.html#regular-expression-syntax">Expresion regular</a> usada para buscar en el texto del BOE.</li>
</ul>
</p>
<h3>BOE del tipo B de licitaciones</h3>
<p>Este BOE es el formato.<br/>Sobre este formato existen las siguientes opciones:
<ul>
<li><b>titulo:</b> <a href="http://docs.python.org/2/library/re.html#regular-expression-syntax">Expresion regular</a> usada para buscar en el titulo.</li>
<li><b>departamento:</b> Es un listado con los distintos departamentos posibles.</li>
<li><b>materias:</b> Es un listado de posibles alerta como parecen en "Alertas de anuncios de licitación" en el servicio oficial.</li>
<li><b>texto:</b> <a href="http://docs.python.org/2/library/re.html#regular-expression-syntax">Expresion regular</a> usada para buscar en el texto del BOE.</li>
</ul>
</p>
</div>
</div>

</div>
</div>

templates/tabla.html
$def with (title, columnas, table_id)
<div class="panel panel-primary">
<div class="panel-heading">$title</div>
<div class="panel-body">
<table cellpadding="0" cellspacing="0" border="0" class="display" id="$table_id">
<thead>
<tr>
$for key in columnas:
	<th width="$key['width']">$key['title'].replace('_',' ')</th>
</tr>
</thead>
<tbody>
<tr>
<td colspan="$len(columnas)" class="dataTables_empty">Cargando datos del servidor</td>
</tr>
</tbody>
<tfoot>
<tr>
$for key in columnas:
	<th>$key['title'].replace('_',' ')</th>
</tr>
</tfoot>
</table>
</div>

<div class="modal fade" id="modal_$table_id" tabindex="-1" role="dialog" aria-labelledby="n_regla_$table_id" aria-hidden="true">
<div class="modal-dialog">
<div class="modal-content">
<div class="modal-header">
<button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
<h4 class="modal-title" id="n_regla_$table_id">Insertar nueva regla</h4>
</div>
<div class="modal-body">
<form id="form_$table_id">
$for key in columnas:
	$if 'input' in key and 'type' in key:
		$if key['type'] == "checkbox":
			<div class="checkbox">
			<label>$key['input'].replace('_',' ') <input name="$key['input']" type="$key['type']" value="true"/></label>
			</div>
		$else:
			<div class="form-group">
			<label for="$key['input']_$table_id">$key['input'].replace('re_','').replace('_',' '):</label>
			<input id="$key['input']_$table_id" name="$key['input']" type="$key['type']" placeholder="$key['input'].replace('re_','').replace('_',' ')" class="form-control" value="" />
			</div>
	$elif 'select' in key:
		<div class="form-group">
		<label for="$key['select']_$table_id">$key['select'].replace('_',' '):</label><select id="$key['select']_$table_id" name="$key['select']" class="form-control"></select>
		</div>
</form>
</div>
<div class="modal-footer">
<button type="button" class="btn btn-default" data-dismiss="modal">Cancelar</button>
<button type="button" class="btn btn-primary" id="guardar_$table_id">Guardar</button>
</div>
</div>
</div>
</div>


</div>